# Generated by Django 3.2.6 on 2021-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210825_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='a_feet',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='a_inch',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='b_feet',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='b_inch',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='c_feet',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='c_inch',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='calculation',
            name='loft',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Accessories',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Countertop',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Finish',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Loft',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Material',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Shape',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='kitchen_details',
            name='layout',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
