# Generated by Django 3.2.6 on 2021-08-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210826_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_details',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.calculation'),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.c_details'),
        ),
    ]
