# Generated by Django 3.2.6 on 2021-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_calculation_kitchen_details_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='loft',
        ),
        migrations.RemoveField(
            model_name='kitchen_details',
            name='Loft',
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='loft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a_inch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b_inch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c_inch',
            field=models.IntegerField(default=0),
        ),
    ]
