# Generated by Django 3.2.6 on 2021-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_constants'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='asacrylic',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='basic_accessories',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='bwpply',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='bwrply',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='essentials',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='glossypu',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='hdhmr',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='intermediate_accessories',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='laminate',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='luxe',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='mrply',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='premium',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='premium_accessories',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='constants',
            name='pvclaminate',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
