# Generated by Django 3.2.6 on 2021-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210909_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
