# Generated by Django 3.2.6 on 2021-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_kitchen_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='date',
            field=models.DateField(default=1089),
        ),
    ]
