# Generated by Django 3.2.6 on 2021-09-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_kitchen_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.c_details'),
        ),
    ]
