# Generated by Django 3.2.6 on 2021-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_kitchen_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='Name',
            field=models.CharField(default='NA', max_length=122),
        ),
    ]
