# Generated by Django 3.2.7 on 2021-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210917_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='Services',
            field=models.TextField(default='NA', max_length=132),
        ),
    ]
