 Generated by Django 3.2.7 on 2021-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_kitchen_details_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_details',
            name='location',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='c_details',
            name='message',
            field=models.TextField(default='NA'),
        ),
    ]
