# Generated by Django 3.2.7 on 2021-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210917_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_details',
            name='email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='c_details',
            name='name',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='c_details',
            name='phone',
            field=models.CharField(default='NA', max_length=12),
        ),
    ]
