# Generated by Django 3.2.7 on 2021-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_kitchen_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_details',
            name='Summary_Pdf',
            field=models.FileField(default='/Summary.pdf', upload_to='pdf/'),
        ),
    ]
