# Generated by Django 3.2.7 on 2021-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_kitchen_details_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='pdf',
            field=models.FileField(upload_to='detaispdf'),
        ),
    ]
