# Generated by Django 3.2.7 on 2021-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_kitchen_details_pdf'),
        ('home', '0032_kitchen_details_summary_pdf'),
    ]

    operations = [
    ]
