# Generated by Django 3.2.7 on 2021-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_merge_20211004_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen_details',
            name='Summary_Pdf',
        ),
        migrations.RemoveField(
            model_name='kitchen_details',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='kitchen_details',
            name='Price',
            field=models.CharField(default='NA', max_length=12),
        ),
    ]
