# Generated by Django 3.2.7 on 2021-10-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20211004_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='city1',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city1',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city10',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city10',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city2',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city2',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city3',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city3',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city4',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city4',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city5',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city5',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city6',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city6',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city7',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city7',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city8',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city8',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city9',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='city9',
            name='Phone',
            field=models.OneToOneField(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Email',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AddField(
            model_name='kitchen_details',
            name='Phone',
            field=models.CharField(default='NA', max_length=12),
        ),
    ]
