# Generated by Django 3.2.7 on 2021-10-08 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20211004_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kitchen_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
    ]
