# Generated by Django 3.2.7 on 2021-10-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211007_2016'),
        ('home', '0035_auto_20211007_1925'),
    ]

    operations = [
    ]
