# Generated by Django 3.2.7 on 2021-10-08 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_templink'),
    ]

    operations = [
        migrations.AddField(
            model_name='templink',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
