# Generated by Django 3.2.7 on 2021-10-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_merge_0002_auto_20211007_2016_0035_auto_20211007_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city1',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city10',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city2',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city3',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city4',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city5',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city6',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city7',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city8',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AlterField(
            model_name='city9',
            name='Phone',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
    ]
